DELETE FROM LGFACTCOLISAGE 
WHERE LGCOL_FACTCOL_ID in (SELECT FCOL_ID FROM FACTCOLISAGE WHERE FCOL_PERIODE = 'Octobre 2020');

UPDATE MVT_STOCK 
SET STK_ETAT = 0, STK_IDFACTCOLISAGE = 0
WHERE STK_IDFACTCOLISAGE in (SELECT FCOL_ID FROM FACTCOLISAGE WHERE FCOL_PERIODE = 'Octobre 2020') ;

DELETE FROM FACTCOLISAGE WHERE FCOL_PERIODE = 'Octobre 2020'

ALTER TABLE [dbo].[CONSTANTES] ADD  [CST_DATE_UPDATE] [datetime] NULL
GO

