ALTER TABLE dbo.PRODUIT ADD
	PRD_BARCHIVE bit NULL
GO	
UPDATE dbo.PRODUIT SET PRD_BARCHIVE = 0
GO
ALTER TABLE dbo.CLIENT ADD
	CLT_BARCHIVE bit NULL
GO	
UPDATE dbo.CLIENT SET CLT_BARCHIVE = 0
GO
ALTER TABLE dbo.FOURNISSEUR ADD
	FRN_BARCHIVE bit NULL
GO	
UPDATE dbo.FOURNISSEUR SET FRN_BARCHIVE = 0
GO
UPDATE CONSTANTES SET CST_DATE_UPDATE = GETDATE()
GO
UPDATE CONSTANTES SET CST_VERSION_BD = '6.1'
GO
