UPDATE SOUSCOMMANDE

SET SCMD_COM_TAUX = FRNC.FRNC_TX_COMM
from SOUSCOMMANDE SCMD 
inner join commande CMD
on SCMD.SCMD_CMD_ID = CMD.CMD_ID
inner join CLIENT CLT
ON CMD.CMD_CLT_ID = CLT.CLT_ID
inner join PARAMETRE PR
on CLT.CLT_TYPE_ID = PR.PAR_ID
inner join FOURNISSEUR FRN
ON SCMD.SCMD_FRN_ID = FRN.FRN_ID
inner join FRN_COMM FRNC
on FRN.FRN_ID = FRNC.FRNC_FRN_ID

WHERE SCMD_COM_TAUX =0 AND SCMD_DATE > '2022-01-01' AND SCMD_ETAT <> 14 AND FRNC.FRNC_TYPE_CLIENT = PR.PAR_CODE;


UPDATE SOUSCOMMANDE
SET SCMD_COM_MONTANT = SCMD_COM_BASE * (SCMD_COM_TAUX /100)
WHERE SCMD_COM_MONTANT = 0 AND SCMD_COM_TAUX <>0
AND SCMD_DATE > '2022-01-01' AND SCMD_ETAT <> 14 AND SCMD_COM_BASE <>0
