UPDATE LIGNE_COMMANDE
SET LIGNE_COMMANDE.LGCM_TXCOMM=  FRN_COMM.FRNC_TX_COMM, 
 LIGNE_COMMANDE.LGCM_MTCOMM=  LGCM_PRIX_HT * (FRN_COMM.FRNC_TX_COMM /100)
FROM            PRODUIT INNER JOIN
                         FOURNISSEUR ON PRODUIT.PRD_FRN_ID = FOURNISSEUR.FRN_ID INNER JOIN
                         LIGNE_COMMANDE INNER JOIN
                         COMMANDE ON LIGNE_COMMANDE.LGCM_CMD_ID = COMMANDE.CMD_ID ON PRODUIT.PRD_ID = LIGNE_COMMANDE.LGCM_PRD_ID AND PRODUIT.PRD_DOSSIER = COMMANDE.CMD_ORIGINE INNER JOIN
                         CLIENT ON COMMANDE.CMD_CLT_ID = CLIENT.CLT_ID INNER JOIN
                         FRN_COMM ON FOURNISSEUR.FRN_ID = FRN_COMM.FRNC_FRN_ID INNER JOIN
                         PARAMETRE ON CLIENT.CLT_TYPE_ID = PARAMETRE.PAR_ID AND FRN_COMM.FRNC_TYPE_CLIENT = PARAMETRE.PAR_CODE
WHERE        (COMMANDE.CMD_DATE > CONVERT(DATETIME, '2022-05-01 00:00:00', 102)) AND (LIGNE_COMMANDE.LGCM_TXCOMM = 0) AND (COMMANDE.CMD_ETAT <> 3) AND (COMMANDE.CMD_ORIGINE = N'VINICOM')