ALTER TABLE PRODUIT ADD  PRD_TARIFD float;
GO
UPDATE PRODUIT SET PRD_TARIFD = PRD_TARIFC60B;
GO
UPDATE PRODUIT SET PRD_TARIFC60B = 0;
GO
/** Supprimer manuellement la contrainte codetarif sur la tavle client **/
DROP TABLE IF EXISTS CLIENT_SAV;
GO
SELECT *
INTO CLIENT_SAV
FROM CLIENT;
GO
ALTER TABLE CLIENT ADD  CLT_CODETARIFNEW varchar(max)
GO
UPDATE CLIENT SET CLT_CODETARIFNEW = CLT_CODETARIF
GO
EXEC sp_rename 'dbo.CLIENT.CLT_CODETARIF', 'CLT_CODETARIFOLD', 'COLUMN';
GO
EXEC sp_rename 'dbo.CLIENT.CLT_CODETARIFNEW', 'CLT_CODETARIF', 'COLUMN';
GO
UPDATE CLIENT SET CLT_CODETARIF = 'C120b' where CLT_CODETARIFOLD = 'C';
GO
