ALTER TABLE PRODUIT ADD  PRD_TARIFC120B float;
ALTER TABLE PRODUIT ADD  PRD_TARIFC60B float;
ALTER TABLE PRODUIT ADD  PRD_TARIFC36B float;
ALTER TABLE PRODUIT ADD  PRD_TARIFE float;
UPDATE PRODUIT SET PRD_TARIFC120B = PRD_TARIFC, PRD_TARIFC60B = PRD_TARIFD, PRD_TARIFC36B=0, PRD_TARIFE=0;
ALTER TABLE PRODUIT DROP COLUMN PRD_TARIFC ;
ALTER TABLE PRODUIT DROP COLUMN PRD_TARIFD ;
