DELETE FROM PRODUIT WHERE PRD_MOT_CLE = 'NEW2';

insert into PRODUIT
(PRD_CODE,PRD_MOT_CLE,PRD_MIL,PRD_DISPO,PRD_LIBELLE,PRD_CODE_STAT,PRD_STOCK,PRD_TARIFA,PRD_TARIFB,PRD_TARIFC,PRD_DOSSIER, PRD_DEPOT,PRD_COUL_ID, PRD_CONT_ID, PRD_RGN_ID, PRD_TVA_ID, PRD_COND_ID)
SELECT PRD_CODE,'NEW2',PRD_MIL,PRD_DISPO,PRD_LIBELLE,PRD_CODE_STAT,PRD_STOCK,PRD_TARIFA,PRD_TARIFB,PRD_TARIFC,PRD_DOSSIER, '02',14,2,26,3,43 
from BaseProduit05
