DROP INDEX IF EXISTS FACTTRP$FTRP_DATE on FACTTRP
GO
ALTER TABLE FACTTRP
ALTER COLUMN FTRP_DATE date
GO
CREATE INDEX FACTTRP$FTRP_DATE on FACTTRP (FTRP_DATE)
GO
DROP INDEX IF EXISTS FACTCOM$FCT_DATE_STAT on FACTCOM
ALTER TABLE FACTCOM
ALTER COLUMN FCT_DATE date
GO
ALTER TABLE FACTCOM
ALTER COLUMN FCT_DATE_STAT date
GO
CREATE INDEX FACTCOM$FCT_DATE_STAT on FACTCOM (FCT_DATE_STAT)
GO

ALTER TABLE FACTCOLISAGE
ALTER COLUMN FCOL_DATE date
GO

ALTER TABLE FACTHBV
ALTER COLUMN FHBV_DATE date
GO
