ALTER TABLE CONSTANTES ADD  CST_BSTOCKIT bit;
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_FTP1_URL varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_FTP1_USER varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_FTP1_PWD varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_FTP1_DOSSIER varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_FTP2_URL varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_FTP2_USER varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_FTP2_PWD varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_FTP2_DOSSIER varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_NOMCLIENT varchar(max);
GO
UPDATE CONSTANTES SET CST_VERSION_BD = '5.5'
GO
UPDATE CONSTANTES SET CST_BSTOCKIT = 1;
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_NOMSTOCKEUR varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_TYPEBL varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_TYPELIGNE1 varchar(max);
GO
ALTER TABLE CONSTANTES ADD  CST_STOCKIT_TYPELIGNE2 varchar(max);
GO
