
/*****
 RECALCUL DES ID DE LA TABLE PRECOMMANDE
 *****/
 

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* CREATION d'UNE TABLE TEMPORAIRE */
/*================================ */
CREATE TABLE [dbo].[PRECOMMANDE2](
	[PCMD_ID] [int] IDENTITY(1,1) NOT NULL,
	[PCMD_CLT_ID] [int] NOT NULL,
	[PCMD_PRD_ID] [int] NOT NULL,
	[PCMD_QTE_DERN] [int] NULL,
	[PCMD_QTE_HAB] [int] NULL,
	[PCMD_PRIXU] [money] NULL,
	[PCMD_DATEDERNCMD] [datetime] NULL,
	[PCMD_REFDERNCMD] [nvarchar](50) NULL,
 CONSTRAINT [PRECOMMANDE$PrimaryKey2] PRIMARY KEY CLUSTERED 
(
	[PCMD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRECOMMANDE2] ADD  DEFAULT ((0)) FOR [PCMD_CLT_ID]
GO

ALTER TABLE [dbo].[PRECOMMANDE2] ADD  DEFAULT ((0)) FOR [PCMD_PRD_ID]
GO

ALTER TABLE [dbo].[PRECOMMANDE2] ADD  DEFAULT ((0)) FOR [PCMD_QTE_DERN]
GO

ALTER TABLE [dbo].[PRECOMMANDE2] ADD  DEFAULT ((0)) FOR [PCMD_QTE_HAB]
GO

ALTER TABLE [dbo].[PRECOMMANDE2] ADD  DEFAULT ((0)) FOR [PCMD_PRIXU]
GO

ALTER TABLE [dbo].[PRECOMMANDE2]  WITH CHECK ADD  CONSTRAINT [FK_PRECOMMANDE_CLIENT2] FOREIGN KEY([PCMD_CLT_ID])
REFERENCES [dbo].[CLIENT] ([CLT_ID])
GO

ALTER TABLE [dbo].[PRECOMMANDE2] CHECK CONSTRAINT [FK_PRECOMMANDE_CLIENT2]
GO

ALTER TABLE [dbo].[PRECOMMANDE2]  WITH CHECK ADD  CONSTRAINT [FK_PRECOMMANDE_PRODUIT2] FOREIGN KEY([PCMD_PRD_ID])
REFERENCES [dbo].[PRODUIT] ([PRD_ID])
GO

ALTER TABLE [dbo].[PRECOMMANDE2] CHECK CONSTRAINT [FK_PRECOMMANDE_PRODUIT2]
GO

/* TRANFERT DES DONNEES */
/*================================ */

insert into PRECOMMANDE2 (PCMD_CLT_ID,PCMD_PRD_ID, PCMD_QTE_DERN, PCMD_QTE_HAB,PCMD_PRIXU, PCMD_DATEDERNCMD, PCMD_REFDERNCMD)
SELECT PCMD_CLT_ID,PCMD_PRD_ID, PCMD_QTE_DERN, PCMD_QTE_HAB,PCMD_PRIXU, PCMD_DATEDERNCMD, PCMD_REFDERNCMD from PRECOMMANDE
GO

/* RENOMMER LA TABLE ACTUELLE EN OLD */
/*================================ */
EXEC sp_rename 'PRECOMMANDE', 'PRECOMMANDEOLD';
GO
EXEC sp_rename 'FK_PRECOMMANDE_PRODUIT', 'FK_PRECOMMANDE_PRODUITOLD';
GO
EXEC sp_rename 'FK_PRECOMMANDE_CLIENT', 'FK_PRECOMMANDE_CLIENTOLD';
GO
EXEC sp_rename 'PRECOMMANDE$PrimaryKey', 'PRECOMMANDE$PrimaryKeyOLD';
GO

/* RENOMMER LA TABLE TEMPORAIRE EN NORMAL */
/*======================================= */

EXEC sp_rename 'PRECOMMANDE2', 'PRECOMMANDE';
GO
EXEC sp_rename 'FK_PRECOMMANDE_PRODUIT2', 'FK_PRECOMMANDE_PRODUIT';
GO
EXEC sp_rename 'FK_PRECOMMANDE_CLIENT2', 'FK_PRECOMMANDE_CLIENT';
GO
EXEC sp_rename 'PRECOMMANDE$PrimaryKey2', 'PRECOMMANDE$PrimaryKey';
GO
