ALTER VIEW [dbo].[LST_FACTCOL]
AS
SELECT        FACTCOLISAGE.FCOL_ID, FACTCOLISAGE.FCOL_CODE, FACTCOLISAGE.FCOL_DATE, FACTCOLISAGE.FCOL_FRN_ID, FACTCOLISAGE.FCOL_TOTAL_TAXES, FACTCOLISAGE.FCOL_TOTAL_HT, FACTCOLISAGE.FCOL_TOTAL_TTC, 
                         FACTCOLISAGE.FCOL_PERIODE, FACTCOLISAGE.FCOL_ETAT, FACTCOLISAGE.FCOL_COM_FACT, FACTCOLISAGE.FCOL_IDMODEREGLEMENT, RQ_REGLEMENT.MONTANT AS MONTANT_REGLEMENT, 
                         SUM(LGFACTCOLISAGE.LGCOL_QTE) AS TOTALCOLIS
FROM            FACTCOLISAGE INNER JOIN
                         LGFACTCOLISAGE ON FACTCOLISAGE.FCOL_ID = LGFACTCOLISAGE.LGCOL_FACTCOL_ID LEFT OUTER JOIN
                         RQ_REGLEMENT ON FACTCOLISAGE.FCOL_ID = RQ_REGLEMENT.ID AND RQ_REGLEMENT.TYPE = 14
GROUP BY FACTCOLISAGE.FCOL_ID, FACTCOLISAGE.FCOL_CODE, FACTCOLISAGE.FCOL_DATE, FACTCOLISAGE.FCOL_FRN_ID, FACTCOLISAGE.FCOL_TOTAL_TAXES, FACTCOLISAGE.FCOL_TOTAL_HT, FACTCOLISAGE.FCOL_TOTAL_TTC, 
                         FACTCOLISAGE.FCOL_PERIODE, FACTCOLISAGE.FCOL_ETAT, FACTCOLISAGE.FCOL_COM_FACT, FACTCOLISAGE.FCOL_IDMODEREGLEMENT, RQ_REGLEMENT.MONTANT;
GO
