SELECT CLT_ID, CLT_NOM, CLT_TYPE_ID, CLT_ORIGINE FROM CLIENT 
WHERE NOT CLT_ORIGINE IS NULL
GO
UPDATE CLIENT SET CLT_ORIGINE = 'VINICOM'
WHERE CLT_TYPE_ID <>86
GO
UPDATE CLIENT SET CLT_ORIGINE = 'HOBIVIN'
where clt_rs like '%hobivin%' and CLT_TYPE_ID <>86
GO
