ALTER TABLE CONSTANTES ADD
	CST_TRP_PARTTRP float NULL,
	CST_SOC2_COMPTEPRODUIT_TAXEGO float NULL
GO
UPDATE CONSTANTES SET CST_VERSION_BD = '5.6'
GO
-- REMISE A l'ETAT INITIAL

UPDATE EXPORTPARAM 
SET EXP_VALEUR = 'HT' 
WHERE EXP_TYPE = 'TRP' AND EXP_NLIGNE=6 AND EXP_NCHAMPS=9
GO
DELETE EXPORTPARAM WHERE EXP_TYPE='TRP' AND EXP_NLIGNE=7
GO
-- HT-> HT_HORSTAXEGO
UPDATE EXPORTPARAM 
SET EXP_VALEUR = 'HT_HORSTAXEGO' 
WHERE EXP_TYPE = 'TRP' AND EXP_NLIGNE=6 AND EXP_NCHAMPS=9
GO
-- Création de la ligne 7 à partir de la ligne 6
INSERT INTO [dbo].[EXPORTPARAM]
           ([EXP_TYPE]
           ,[EXP_NLIGNE]
           ,[EXP_NCHAMPS]
           ,[EXP_TYPECHAMPS]
           ,[EXP_VALEUR]
           ,[EXP_LONGUEUR]
           ,[EXP_DESCRIPTION])
    SELECT EXP_TYPE
           ,7
           ,[EXP_NCHAMPS]
           ,[EXP_TYPECHAMPS]
           ,[EXP_VALEUR]
           ,[EXP_LONGUEUR]
           ,[EXP_DESCRIPTION] FROM EXPORTPARAM WHERE EXP_TYPE= 'TRP' AND EXP_NLIGNE=6
GO
-- sur la ligne 7 Montant = 'HT_TAXEGO'
UPDATE EXPORTPARAM 
SET EXP_VALEUR = 'HT_TAXEGO' 
WHERE EXP_TYPE = 'TRP' AND EXP_NLIGNE=7 AND EXP_NCHAMPS=9
GO
UPDATE EXPORTPARAM 
SET EXP_VALEUR = 'COMPTETAXEGO' 
WHERE EXP_TYPE = 'TRP' AND EXP_NLIGNE=7 AND EXP_NCHAMPS=2
GO
