'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("vini_app.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cloud_Mail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cloud+Mail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cloud50x50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cloud50x50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeleteHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FlecheBas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FlecheBas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FlecheEgal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FlecheEgal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FlecheHaut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FlecheHaut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HobivinLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HobivinLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mail50x50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail50x50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewDocumentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDocumentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property openHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RefreshDocViewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exportation vers comptabilité terminée avec des erreurs.
        '''</summary>
        Friend ReadOnly Property STR_EXPORTCOMPTA_NOK() As String
            Get
                Return ResourceManager.GetString("STR_EXPORTCOMPTA_NOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exportation vers comptabilité terminée avec succès.
        '''</summary>
        Friend ReadOnly Property STR_EXPORTCOMPTA_OK() As String
            Get
                Return ResourceManager.GetString("STR_EXPORTCOMPTA_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Répertoire d&apos;exportation pour la compatabilité.
        '''</summary>
        Friend ReadOnly Property STR_EXPORTCOMPTA_PATH() As String
            Get
                Return ResourceManager.GetString("STR_EXPORTCOMPTA_PATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cette ligne n&apos;est pas modifiable dans cet état.
        '''</summary>
        Friend ReadOnly Property STR_LIGNE_NON_MODIFIABLE() As String
            Get
                Return ResourceManager.GetString("STR_LIGNE_NON_MODIFIABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous valider l&apos;export des factures.
        '''</summary>
        Friend ReadOnly Property STR_VALIDATION_EXPORT_FACTURE() As String
            Get
                Return ResourceManager.GetString("STR_VALIDATION_EXPORT_FACTURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous valider l&apos;export des règlements.
        '''</summary>
        Friend ReadOnly Property STR_VALIDATION_EXPORT_REGLEMENT() As String
            Get
                Return ResourceManager.GetString("STR_VALIDATION_EXPORT_REGLEMENT", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
